# Nome do seu workflow
name: Deploy Blazor WASM to GitHub Pages

# Define o gatilho: rodar quando houver um push no branch main
on:
  push:
    branches: [ main ]

# Permissões necessárias para o job poder publicar no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código do seu repositório
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Instala a versão correta do .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Use a versão do seu projeto

      # 3. Publica a aplicação Blazor WebAssembly
      # O resultado ficará na pasta 'publish/wwwroot'
      - name: Publish .NET Project
        run: dotnet publish DiagramaDeClasse.csproj -c Release -o release --nologo
        # IMPORTANTE: Troque 'DiagramaDeClasse.csproj' pelo nome real do seu arquivo .csproj

      # 4. Adiciona um arquivo .nojekyll para evitar problemas com o Jekyll do GitHub Pages
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      # 5. Corrige o problema de refresh em rotas (Erro 404)
      # Copia o index.html para 404.html para que o Blazor Router cuide das rotas
      - name: Rewrite base href for GH Pages
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: release/wwwroot/index.html
          base_href: /DiagramaDeClasse/ 

      # 6. Copia o index.html para 404.html para lidar com o roteamento do Blazor
      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # 7. Prepara os arquivos para serem enviados ao GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot

      # 8. Faz o deploy dos arquivos no GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4